---
- hosts: workstation

  tasks:
    - name: install brew packages
      homebrew: name={{item}} state=latest
      with_items:
        - coreutils
        - moreutils
        - findutils  # Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
        - bash
        - bash-completion
        - gnu-sed
        - wget
        - vim
        - ack
        - git
        - tree
        - p7zip
        - bfg # Install some CTF tools; see https://github.com/ctfs/write-ups
        - binutils
        - cifer
        - dex2jar
        - dns2tcp
        - fcrackzip
        - foremost
        - hashpump
        - hydra
        - john
        - knock
        - nmap
        - pngcheck
        - socat
        - sqlmap
        - tcpflow
        - tcpreplay
        - tcptrace
        - ucspi-tcp # `tcpserver` etc.
        - xz
        - cowsay # extra packages
        - go
        - nvm
        - mysql
      notify:
        - create sha256sum bin
    - name: nvm dir
      file: dest=~/.nvm state=directory
    - name: nvm config
      lineinfile: dest=~/.bash_profile
        regexp='^# nvm'
        line='# nvm'
        insertafter=EOF
        state=present
    - name: nvm source
      lineinfile: dest=~/.bash_profile
        regexp='^source '
        line='source $(brew --prefix nvm)/nvm.sh'
        insertafter='^# nvm'
        state=present
    - name: nvm export
      lineinfile: dest=~/.bash_profile
        regexp='^export NVM_DIR=~/.nvm'
        line='export NVM_DIR=~/.nvm'
        insertafter='^source '
        state=present
    - name: install rvm
      shell: curl -sSL https://get.rvm.io | bash -s stable
      shell: source ~/.bash_profile
    - name: install grep
      shell: brew install homebrew/dupes/grep
    - name: install grep
      shell: brew install homebrew/dupes/screen
    - name: install php55
      shell: brew install homebrew/php/php55
    - name: install brew cask
      shell: brew install caskroom/cask/brew-cask

    - name: install postgresql
      homebrew: name=postgresql state=latest
    - name: create LaunchAgents dir
      file: dest=~/Library/LaunchAgents state=directory
    - name: symlink postgresql.plist
      file: src=/usr/local/opt/postgresql/homebrew.mxcl.postgresql.plist dest=~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist state=link
    - name:
      shell: launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
    - name: drop user pahko
      shell: psql -d template1 -c "DROP ROLE IF EXISTS pahko;"
    - name: create pahko user
      shell: psql -d template1 -c "CREATE ROLE pahko;"

  handlers:
    - name: create sha256sum bin
      file: src=/usr/local/bin/gsha256sum dest=/usr/local/bin/sha256sum state=link

